create table public.profiles (
  id uuid not null,
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone not null default now(),
  first_name character varying null,
  last_name character varying null,
  email text null,
  is_superadmin boolean not null default false,
  is_in_study boolean not null default false,
  is_matrix_admin boolean not null default false,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  constraint profiles_pkey primary key (id),
  constraint profiles_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint profiles_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;


CREATE OR REPLACE FUNCTION public.set_created_and_modified_by_user_ids()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO 'public', 'pg_temp'
AS $function$
declare
  audit_user_id uuid;
begin
  audit_user_id := auth.uid();

  if audit_user_id is null and tg_table_schema = 'public' and tg_table_name = 'profiles' then
    audit_user_id := new.id;
  end if;

  if tg_op = 'INSERT' then
    new.created_by_user_id := coalesce(new.created_by_user_id, audit_user_id);
    new.modified_by_user_id := coalesce(
      new.modified_by_user_id,
      new.created_by_user_id,
      audit_user_id
    );
  elsif tg_op = 'UPDATE' then
    new.created_by_user_id := coalesce(
      new.created_by_user_id,
      old.created_by_user_id,
      audit_user_id
    );
    new.modified_by_user_id := coalesce(
      audit_user_id,
      new.modified_by_user_id,
      old.modified_by_user_id,
      new.created_by_user_id
    );
  end if;

  return new;
end;
$function$







CREATE OR REPLACE FUNCTION public.set_modified_datetime_utc()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.modified_datetime_utc = now();
  return new;
end;
$function$









create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on profiles for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on profiles for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.images (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone not null default now(),
  url character varying null,
  is_common_use boolean null default false,
  profile_id uuid null default auth.uid (),
  additional_context character varying null,
  is_public boolean null default false,
  image_description text null,
  celebrity_recognition text null,
  embedding public.vector null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  constraint images_pkey primary key (id),
  constraint images_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint images_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null,
  constraint images_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_images_is_common_use on public.images using btree (is_common_use) TABLESPACE pg_default
where
  (is_common_use = true);

create index IF not exists idx_images_is_public on public.images using btree (is_public) TABLESPACE pg_default
where
  (is_public = true);

create index IF not exists idx_images_profile_id on public.images using btree (profile_id) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on images for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on images for EACH row
execute FUNCTION set_modified_datetime_utc ();




create table public.humor_flavors (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  description text null,
  slug character varying not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint humor_flavors_pkey primary key (id),
  constraint humor_flavors_slug_key unique (slug),
  constraint humor_flavors_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint humor_flavors_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on humor_flavors for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on humor_flavors for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.humor_flavor_steps (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  humor_flavor_id bigint not null,
  llm_temperature numeric null,
  order_by smallint not null,
  llm_input_type_id smallint not null,
  llm_output_type_id smallint not null,
  llm_model_id smallint not null,
  humor_flavor_step_type_id smallint not null,
  llm_system_prompt text null,
  llm_user_prompt text null,
  description character varying null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint humor_flavor_steps_pkey primary key (id),
  constraint humor_flavor_steps_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on update CASCADE on delete CASCADE,
  constraint humor_flavor_steps_humor_flavor_step_id_fkey foreign KEY (humor_flavor_step_type_id) references humor_flavor_step_types (id),
  constraint humor_flavor_steps_llm_input_type_id_fkey foreign KEY (llm_input_type_id) references llm_input_types (id),
  constraint humor_flavor_steps_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint humor_flavor_steps_llm_output_type_id_fkey foreign KEY (llm_output_type_id) references llm_output_types (id),
  constraint humor_flavor_steps_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null,
  constraint humor_flavor_steps_llm_model_id_fkey foreign KEY (llm_model_id) references llm_models (id) on update CASCADE
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on humor_flavor_steps for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on humor_flavor_steps for EACH row
execute FUNCTION set_modified_datetime_utc ();

create trigger trg_set_modified_datetime_utc_humor_flavor_steps BEFORE
update on humor_flavor_steps for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.humor_flavor_step_types (
  id smallint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  slug character varying not null,
  description text not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  created_datetime_utc timestamp with time zone not null default now(),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint humor_flavor_step_types_pkey primary key (id),
  constraint humor_flavor_step_types_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint humor_flavor_step_types_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on humor_flavor_step_types for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on humor_flavor_step_types for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.llm_models (
  id smallint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  name character varying not null,
  llm_provider_id smallint not null,
  provider_model_id character varying not null,
  is_temperature_supported boolean not null default false,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint caption_generation_models_pkey primary key (id),
  constraint llm_models_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint llm_models_llm_provider_id_fkey foreign KEY (llm_provider_id) references llm_providers (id),
  constraint llm_models_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on llm_models for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on llm_models for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.llm_providers (
  id smallint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  name character varying not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint llm_providers_pkey primary key (id),
  constraint llm_providers_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint llm_providers_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on llm_providers for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on llm_providers for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.llm_prompt_chains (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  caption_request_id bigint not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint llm_prompt_chains_pkey primary key (id),
  constraint llm_prompt_chains_caption_request_id_fkey foreign KEY (caption_request_id) references caption_requests (id) on delete CASCADE,
  constraint llm_prompt_chains_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint llm_prompt_chains_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on llm_prompt_chains for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on llm_prompt_chains for EACH row
execute FUNCTION set_modified_datetime_utc ();







create table public.llm_model_responses (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default now(),
  llm_model_response text null,
  processing_time_seconds smallint not null,
  llm_model_id smallint not null,
  profile_id uuid not null,
  caption_request_id bigint not null,
  llm_system_prompt text not null,
  llm_user_prompt text not null,
  llm_temperature numeric null,
  humor_flavor_id bigint not null,
  llm_prompt_chain_id bigint null,
  humor_flavor_step_id bigint null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint llm_model_responses_pkey primary key (id),
  constraint llm_model_responses_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint llm_model_responses_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on delete CASCADE,
  constraint llm_model_responses_humor_flavor_step_id_fkey foreign KEY (humor_flavor_step_id) references humor_flavor_steps (id) on delete CASCADE,
  constraint llm_model_responses_llm_model_id_fkey foreign KEY (llm_model_id) references llm_models (id),
  constraint llm_model_responses_llm_prompt_chain_id_fkey foreign KEY (llm_prompt_chain_id) references llm_prompt_chains (id) on delete CASCADE,
  constraint llm_model_responses_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null,
  constraint llm_model_responses_caption_request_id_fkey foreign KEY (caption_request_id) references caption_requests (id) on update CASCADE on delete CASCADE,
  constraint llm_model_responses_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on llm_model_responses for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on llm_model_responses for EACH row
execute FUNCTION set_modified_datetime_utc ();







create table public.caption_requests (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  profile_id uuid not null,
  image_id uuid not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint caption_requests_pkey primary key (id),
  constraint caption_requests_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint caption_requests_image_id_fkey foreign KEY (image_id) references images (id) on delete CASCADE,
  constraint caption_requests_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null,
  constraint caption_requests_profile_id_fkey foreign KEY (profile_id) references profiles (id) on update CASCADE
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on caption_requests for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on caption_requests for EACH row
execute FUNCTION set_modified_datetime_utc ();








create table public.captions (
  id uuid not null default gen_random_uuid (),
  created_datetime_utc timestamp with time zone not null default CURRENT_TIMESTAMP,
  modified_datetime_utc timestamp with time zone not null default CURRENT_TIMESTAMP,
  content character varying null,
  is_public boolean not null,
  profile_id uuid not null,
  image_id uuid not null,
  humor_flavor_id bigint null,
  is_featured boolean not null default false,
  caption_request_id bigint null,
  like_count bigint not null default '0'::bigint,
  llm_prompt_chain_id bigint null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  constraint captions_pkey primary key (id),
  constraint captions_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint captions_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on delete set null,
  constraint captions_image_id_fkey foreign KEY (image_id) references images (id) on delete CASCADE,
  constraint captions_llm_prompt_chain_id_fkey foreign KEY (llm_prompt_chain_id) references llm_prompt_chains (id) on delete CASCADE,
  constraint captions_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null,
  constraint captions_caption_request_id_fkey foreign KEY (caption_request_id) references caption_requests (id) on update CASCADE on delete CASCADE,
  constraint captions_profile_id_fkey foreign KEY (profile_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create index IF not exists idx_captions_image_id on public.captions using btree (image_id) TABLESPACE pg_default;

create index IF not exists idx_captions_like_count_desc_id on public.captions using btree (like_count desc, id) TABLESPACE pg_default;

create index IF not exists captions_image_id_idx on public.captions using btree (image_id) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on captions for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on captions for EACH row
execute FUNCTION set_modified_datetime_utc ();




create table public.humor_flavor_mix (
  id bigint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  humor_flavor_id bigint not null,
  caption_count smallint not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint humor_flavor_mix_pkey primary key (id),
  constraint humor_flavor_mix_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint humor_flavor_mix_humor_flavor_id_fkey foreign KEY (humor_flavor_id) references humor_flavors (id) on delete CASCADE,
  constraint humor_flavor_mix_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on humor_flavor_mix for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on humor_flavor_mix for EACH row
execute FUNCTION set_modified_datetime_utc ();






create table public.llm_input_types (
  id smallint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  description character varying not null,
  slug character varying not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint llm_input_types_pkey primary key (id),
  constraint llm_input_types_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint llm_input_types_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on llm_input_types for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on llm_input_types for EACH row
execute FUNCTION set_modified_datetime_utc ();







create table public.llm_output_types (
  id smallint generated by default as identity not null,
  created_datetime_utc timestamp with time zone not null default now(),
  description character varying not null,
  slug character varying not null,
  created_by_user_id uuid not null default auth.uid (),
  modified_by_user_id uuid not null default auth.uid (),
  modified_datetime_utc timestamp with time zone not null default now(),
  constraint llm_output_types_pkey primary key (id),
  constraint llm_output_types_created_by_user_id_fkey foreign KEY (created_by_user_id) references profiles (id) on delete set null,
  constraint llm_output_types_modified_by_user_id_fkey foreign KEY (modified_by_user_id) references profiles (id) on delete set null
) TABLESPACE pg_default;

create trigger set_created_and_modified_by_user_ids_before_write BEFORE INSERT
or
update on llm_output_types for EACH row
execute FUNCTION set_created_and_modified_by_user_ids ();

create trigger set_modified_datetime_utc_before_update BEFORE
update on llm_output_types for EACH row
execute FUNCTION set_modified_datetime_utc ();






